# Generated by Django 4.1.2 on 2023-01-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='to_comment',
        ),
    ]
